// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgbN-RwGXUgGGHMTlOd3TWYbFC7Ff_eLs',
    appId: '1:1012416922510:web:b9c78e4b2e36dbd6841adf',
    messagingSenderId: '1012416922510',
    projectId: 'vmsa-391ad',
    authDomain: 'vmsa-391ad.firebaseapp.com',
    storageBucket: 'vmsa-391ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-ibaY5MVK1ShdE5rS3RN_EMS2ReN67g',
    appId: '1:1012416922510:android:ebbaf9349c07d685841adf',
    messagingSenderId: '1012416922510',
    projectId: 'vmsa-391ad',
    storageBucket: 'vmsa-391ad.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsIShc90U54iuf_fqXs5lFf04ze5mi6MY',
    appId: '1:1012416922510:ios:fcb414c47846b7b2841adf',
    messagingSenderId: '1012416922510',
    projectId: 'vmsa-391ad',
    storageBucket: 'vmsa-391ad.firebasestorage.app',
    iosBundleId: 'com.example.vaccineAapp',
  );
}
